default: &default
  adapter: mysql2
#  host: localhost
#  username: <%= ENV['MYSQL_USER'] %>
#  password: <%= ENV['MYSQL_PASS'] %>
  url: 'mysql2://root@localhost:3306/student_mgt'
development:
  primary:
    <<: *default
    database: student_mgt